### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [supanutjarukulgowit/google_search_web_api#13]
Hello  👋 , thank you for your effort on the code submission. I am Olivier at Nimble and am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would also love to hear back from you. Therefore, do not hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs. I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us immediately so we can plan accordingly.

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
For the code challenge, we expected you to implement the Web scraping without using a third-party service provider (such as https://serpapi.com/). Doing so would have required you to use HTML parsing libraries and background processing. While you will not be penalized for using the API service, you should have checked with our team prior to do the implementation 😅

**Comment by olivierobert** [comment]
I have completed the initial round of review. Note that I have also opened https://github.com/supanutjarukulgowit/google_search_web_app/issues/7 on the other repository. 

We do not aim to raise every single issue as this would take too long, and we aim to keep the code review process short. The goal is to get your feedback on these issues so that we can better understand your technical implementation choices.

**Comment by supanutjarukulgowit** [comment]
> For the code challenge, we expected you to implement the Web scraping without using a third-party service provider (such as https://serpapi.com/). Doing so would have required you to use HTML parsing libraries and background processing. While you will not be penalized for using the API service, you should have checked with our team prior to do the implementation 😅

Sorry for that this is my mistake. I've nerver done any web scraping project before if I understand correctly web scraping is the way you get any data from html content. So this is make it so much easier than getting data from third-party service provider. I just have to know the tag, id or class name of some data that I want. Thank you for the review.

**Comment by olivierobert** [comment]
> I've never done any web scraping project before

That's one of the motivations. Most applicants have never done it, so it requires doing some research. In software development, it is normal to work on things for the first time, hence the idea is to see how you can come up with a solution for a novel issue.

**Comment by olivierobert** [comment]
I have reviewed the open pull requests and comments on all the open issues. So it is time to wrap up this stage of the code review process.

Thank you for your efforts so far. Our team will provide feedback to you by email shortly.
